SELECT 
	  EMP.DEPARTMENT		AS EMP_DEPT
	, EMP.FIRST_NAME		AS EMP_FNAME
	, EMP.LAST_NAME			AS EMP_LNAME
	, SUM(EMP.UNITS_SOLD)   AS EMP_UNITS_SOLD
FROM 
	  EMPLOYEE AS EMP
GROUP BY
	  EMP.DEPARTMENT
	, EMP.FIRST_NAME
	, EMP.LAST_NAME
ORDER BY
	  EMP_DEPT
	, EMP_UNITS_SOLD
	, EMP_LNAME
	, EMP_FNAME


	  