SELECT 
	  CHK.ACCOUNT_NUMBER 	         AS ACC_NUM
	, CHK.ACCOUNT_TOTAL		 AS CHK_TOTAL
	, COALESCE(SAV.ACCOUNT_TOTAL, 0) AS SAV_TOTAL
FROM 
	  CHECKING AS CHK
     LEFT OUTER JOIN
	  SAVINGS AS SAV
     ON   CHK.ACCOUNT_NUMBER = SAV.ACCOUNT_NUMBER
WHERE 
	  CHK.ACCOUNT_NUMBER BETWEEN (1000 AND 2000)


	  
